// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPlxaVKAlXAiCE3ZKur9g0UK5NLIAu4GY',
    appId: '1:831450917436:web:d69b81ae241cbdbdd6f139',
    messagingSenderId: '831450917436',
    projectId: 'todo-1ba7b',
    authDomain: 'todo-1ba7b.firebaseapp.com',
    storageBucket: 'todo-1ba7b.appspot.com',
    measurementId: 'G-9XHPYKX69Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbe01MPx2CM7b1c_KHkdPYXw7WwP9CVoA',
    appId: '1:831450917436:android:cecd32d8bb0d79e0d6f139',
    messagingSenderId: '831450917436',
    projectId: 'todo-1ba7b',
    storageBucket: 'todo-1ba7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6eGMLqXn5VNCCJNZPSsGLGyPHITaRKcU',
    appId: '1:831450917436:ios:8dba33c1317be7cdd6f139',
    messagingSenderId: '831450917436',
    projectId: 'todo-1ba7b',
    storageBucket: 'todo-1ba7b.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6eGMLqXn5VNCCJNZPSsGLGyPHITaRKcU',
    appId: '1:831450917436:ios:a44768c0456460eed6f139',
    messagingSenderId: '831450917436',
    projectId: 'todo-1ba7b',
    storageBucket: 'todo-1ba7b.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
